### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by RomanistNLX** [nlxai/voice-compass-sdk#18]
- add a simple editor for the [classlist property](https://github.com/nlxai/voice-compass-portal-backend/blob/master/code/shared/validator/models/Journey.json#L810-L822) in the popup, basically just to set enabled state for each class name. Make some design choices there.
- add a toggle in approximately [the regular UI component style](https://nlxai.github.io/naturalui/?path=/story/toggle--regular) but a bit more compact, to toggle between path and selector mode. Path is the default mode and it shows the path we currently have. Selector just replaces that with an input field that you can write a CSS selector in, updating the trigger.selector property. The trigger.path property is always kept in the data structure, however when the user reselects the path mode on the toggle, the trigger.selector should be cleared.
- ~~when the [StepEditor](https://github.com/nlxai/voice-compass-sdk/blob/master/packages/point-and-click/src/index.tsx#L168-L347) component is on the page with all its global event handlers, would be great to find a way so that clicking on elements on the page do not trigger their own event handlers, only the event handlers inside this component. Feel free to change click to mousedown if that helps. This is helpful to mark 'Continue' buttons on typical journeys in a way that doesn't also change the page at the same time.~~
- search bar for steps if the list is longer than 5 - simple case-insensitive by name and key.
- closing dropdown on click outside

**Comment by peterszerzo** [comment]
Broke this task down into #22, #23, #24 and #25.
