### ISSUE TITLE
UI Template: strategy for complicated screens

### ISSUE THREAD

**Issue by peterszerzo** [nlxai/voice-compass-sdk#3]
This issue is a discussion point to develop strategies to deal with complicated journeys. Such journeys often have many screens and tricky logic, and historically we often just slammed it all together into one `index.svelte` route component. While this is a good idea for many reasons (avoiding abstractions that cause more headache than do good), we should keep an eye out on strategies.

Alternatives:

## Route file for every screen

```
/ src
  / routes
    screen-1.svelte
    screen-2.svelte
    screen-3.svelte
    screen-4.svelte
```

Advantages:
- every screen has its own URL automatically.
- transitioning between screens is a simple `href`.

Disadvantages:
- screen transitions are harder because of component unmount behavior (maybe there's a simple solution but I haven't found it yet).
- need to maintain contact ID *everywhere* in case of a refresh. Putting an abstraction into link components to handle this automatically could work, but it's annoying and has edge cases.

## Subcomponents for every screen

The less intrusive version of this is to create a subcomponent for every screen and wire it all together. This allows for better parent-child communication without stores.

Let's hold off merging actual refactorings before we reached a good decision.

**Comment by chulander** [comment]
need to think about this a bit.

the latter option sounds like not using routes and transition via state and subcomponents?

**Comment by chulander** [comment]
not 100% related but I wonder if using preloading would help any of the component/route transition behavior.

https://sapper.svelte.dev/docs#Preloading

unsure of a use-case yet, need to dive deeper

**Comment by peterszerzo** [comment]
We are no longer providing UI templates in this project.
