### ISSUE TITLE
Developer tooling for Voice Compass SDK

### ISSUE THREAD

**Issue by peterszerzo** [nlxai/voice-compass-sdk#4]
When user creates a voice compass client on the frontend, in addition to `botId`, `apiKey` and `journeyId`, they should also be able to add a `debug` optional boolean flag. When this flag is active, there should be nice logs in the console whenever a step is called, with all related metadata/payload/journey info. This can be simple at first - since we need this sooner rather than later - but eventually we can make it nice the way fancy redux loggers do it.

**Comment by chulander** [comment]
cool, yeah i saw that in the workshop, its the breakpoint that triggers if your console is open. 

https://svelte.dev/tutorial/debug

very cool. I'll start thinking about what needs to be done.

**Comment by chulander** [comment]
looking at the cold, I can't use svelte @debug since the file in question is the an index.ts file. i'll add console.info flags if the debug is passed in as true

**Comment by peterszerzo** [comment]
@chulander this is not a svelte thing, I meant it in the implementation of `updateStep` in the core SDK.
